name: Run EuropaBots on Windows

on:
  workflow_dispatch:

jobs:
  run-europabots:
    runs-on: windows-latest

    steps:
      - name: Download ZIP from Google Drive
        run: |
          Invoke-WebRequest -Uri "https://drive.usercontent.google.com/download?id=1Tm5V1ABjsWiFjHolMgPPFdCBKRR78-iz&export=download&authuser=0" -OutFile "europabots.zip"

      - name: Extract ZIP
        run: |
          Expand-Archive europabots.zip -DestinationPath .

      - name: Replace broken batch file with fixed version
        run: |
          Set-Content -Path ".\EuropaBots\RunAllRakClients.bat" -Value '@echo off
setlocal enabledelayedexpansion

echo Starting RakSAMP Lite for each folder...

for /d %%F in (*) do (
    if exist "%%F\RakSAMP Lite.exe" (
        echo Running: %%F\RakSAMP Lite.exe
        pushd "%%F"
        start "" "RakSAMP Lite.exe"
        popd
        timeout /t 2 /nobreak >nul
    ) else (
        echo Skipping: %%F (RakSAMP Lite.exe not found)
    )
)

echo Done launching all available RakSAMP Lite instances.
pause' -Encoding ASCII

      - name: Run the batch file inside EuropaBots
        working-directory: ./EuropaBots
        run: |
          .\RunAllRakClients.bat
