name: Run EuropaBots on Windows

on:
  workflow_dispatch:

jobs:
  run-europabots:
    runs-on: windows-latest

    steps:
      - name: Download ZIP from Google Drive
        run: |
          Invoke-WebRequest -Uri "https://drive.usercontent.google.com/download?id=1Tm5V1ABjsWiFjHolMgPPFdCBKRR78-iz&export=download&authuser=0" -OutFile "europabots.zip"

      - name: Extract ZIP
        run: |
          Expand-Archive europabots.zip -DestinationPath .

      - name: Replace broken batch file with fixed version
        shell: cmd
        run: |
          echo @echo off > EuropaBots\RunAllRakClients.bat
          echo setlocal enabledelayedexpansion >> EuropaBots\RunAllRakClients.bat
          echo. >> EuropaBots\RunAllRakClients.bat
          echo echo Starting RakSAMP Lite for each folder... >> EuropaBots\RunAllRakClients.bat
          echo. >> EuropaBots\RunAllRakClients.bat
          echo for /d %%%%F in (*) do ( >> EuropaBots\RunAllRakClients.bat
          echo     if exist "%%%%F\RakSAMP Lite.exe" ( >> EuropaBots\RunAllRakClients.bat
          echo         echo Running: %%%%F\RakSAMP Lite.exe >> EuropaBots\RunAllRakClients.bat
          echo         pushd "%%%%F" >> EuropaBots\RunAllRakClients.bat
          echo         start "" "RakSAMP Lite.exe" >> EuropaBots\RunAllRakClients.bat
          echo         popd >> EuropaBots\RunAllRakClients.bat
          echo         timeout /t 2 /nobreak ^>nul >> EuropaBots\RunAllRakClients.bat
          echo     ) else ( >> EuropaBots\RunAllRakClients.bat
          echo         echo Skipping: %%%%F (RakSAMP Lite.exe not found) >> EuropaBots\RunAllRakClients.bat
          echo     ) >> EuropaBots\RunAllRakClients.bat
          echo ) >> EuropaBots\RunAllRakClients.bat
          echo. >> EuropaBots\RunAllRakClients.bat
          echo echo Done launching all available RakSAMP Lite instances. >> EuropaBots\RunAllRakClients.bat
          echo pause >> EuropaBots\RunAllRakClients.bat

      - name: Run the batch file inside EuropaBots
        working-directory: ./EuropaBots
        shell: cmd
        run: |
          RunAllRakClients.bat
