name: Run RakSAMP Lite Clients

on:
  workflow_dispatch:

jobs:
  run-lite-clients:
    runs-on: windows-latest

    steps:
      - name: Download ZIP from Google Drive
        run: |
          Invoke-WebRequest -Uri "https://drive.usercontent.google.com/download?id=1Tm5V1ABjsWiFjHolMgPPFdCBKRR78-iz&export=download&authuser=0" -OutFile "europabots.zip"

      - name: Extract ZIP
        run: |
          Expand-Archive europabots.zip -DestinationPath .

      - name: Launch all RakSAMP Lite.exe clients manually
        shell: pwsh
        working-directory: ./EuropaBots
        run: |
          Get-ChildItem -Directory | ForEach-Object {
            $exePath = Join-Path $_.FullName "RakSAMP Lite.exe"
            if (Test-Path $exePath) {
              Write-Host "Launching: $exePath"
              Start-Process -FilePath "$exePath"
              Start-Sleep -Seconds 2
            } else {
              Write-Host "Skipping: $($_.Name) (no RakSAMP Lite.exe)"
            }
          }
