name: Run RakSAMP Lite Clients

on:
  workflow_dispatch:

jobs:
  run-lite-clients:
    runs-on: windows-latest

    steps:
      - name: Download ZIP from Google Drive (fallback curl)
        shell: bash
        run: |
          FILE_ID=1Tm5V1ABjsWiFjHolMgPPFdCBKRR78-iz
          curl -L -o europabots.zip "https://drive.google.com/uc?export=download&id=${FILE_ID}"

      - name: Extract ZIP
        shell: pwsh
        run: |
          Expand-Archive europabots.zip -DestinationPath .

      - name: Launch RakSAMP Lite clients and monitor
        shell: pwsh
        working-directory: ./EuropaBots
        run: |
          $procs = @()
          $folders = Get-ChildItem -Directory

          foreach ($folder in $folders) {
            $exe = Join-Path $folder.FullName "RakSAMP Lite.exe"
            if (Test-Path $exe) {
              Write-Host "Launching: $exe"
              $proc = Start-Process -FilePath $exe -PassThru
              $procs += $proc
              Start-Sleep -Seconds 5
            } else {
              Write-Host "Skipping: $($folder.Name) (no RakSAMP Lite.exe)"
            }
          }

          Write-Host "All clients launched. Monitoring processes..."

          while ($true) {
            foreach ($p in $procs) {
              if ($p.HasExited) {
                Write-Host "❌ Process $($p.Id) has exited."
              } else {
                Write-Host "✅ Process $($p.Id) is running."
              }
            }
            Start-Sleep -Seconds 60
          }
